export const FETCH_ADDRESS_START = "FETCH_ADDRESS_START";
export const FETCH_ADDRESS_SUCCESS = "FETCH_ADDRESS_SUCCESS";
export const FETCH_ADDRESS_FAIL = "FETCH_ADDRESS_FAIL";


export const ADD_ADDRESS = "ADD_ADDRESS";
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS";
export const ADD_ADDRESS_FAIL = "ADD_ADDRESS_FAIL";

export const EDIT_CELLPHONE = "EDIT_CELLPHONE";
export const EDIT_CELLPHONE_SUCCESS = "EDIT_CELLPHONE_SUCCESS";
export const EDIT_CELLPHONE_FAIL = "EDIT_CELLPHONE_FAIL";

export const EDIT_ADDRESS = "EDIT_ADDRESS";
export const EDIT_ADDRESS_SUCCESS = "EDIT_ADDRESS_SUCCESS";
export const EDIT_ADDRESS_FAIL = "EDIT_ADDRESS_FAIL";

export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAIL = "DELETE_ADDRESS_FAIL";

export const SORT_COLUMN = "SORT_COLUMN";
